name: Docker Image CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/loykrathong:latest .
      - name: Push the Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/loykrathong:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger deployment
        run: |
          curl -X POST ${{secrets.PT_TRIGGER_API}}